# Generated by Django 2.2.9 on 2023-02-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_change_Post_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
