# Generated by Django 2.2.16 on 2023-02-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230214_0200'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_follow',
        ),
    ]
